export const navPages = [
  { label: "Home", href: "/" },
  { label: "Accordion", href: "/app/accordion" },
  { label: "Breadcrumbs", href: "/app/breadcrumbs" },
  { label: "Button", href: "/app/button" },
  { label: "Charts", href: "/app/charts" },
  { label: "CheckBox", href: "/app/checkbox" },
  { label: "Datepicker", href: "/app/datepicker" },
  { label: "Dropdown", href: "/app/dropdown" },
  { label: "Expandable Card", href: "/app/expandable-card" },
  { label: "Feature Card", href: "/app/feature-card" },
  { label: "Flex Card", href: "/app/flex-card" },
  { label: "Label Input", href: "/app/label-input" },
  { label: "Popup Confirm", href: "/app/popup-confirm" },
  { label: "Popup Large", href: "/app/popup-large" },
  { label: "Roadmap", href: "/app/roadmap" },
  { label: "Submit Button", href: "/app/submit-button" },
  { label: "Tags", href: "/app/tags" },
  { label: "Testimonials", href: "/app/testimonials" },
  { label: "Toast", href: "/app/toast" },
];
